personal_add:
    pattern:  /add
    defaults: { _controller: DentoletiPersonalBundle:Default:add }

personal_list:
    pattern: /list
    defaults: { _controller: DentoletiPersonalBundle:Default:list }

personal_search:
    pattern: /search
    defaults: { _controller: DentoletiPersonalBundle:Default:search }

personal_view:
    pattern: /view/{id}
    defaults: { _controller: DentoletiPersonalBundle:Default:view }

personal_edit:
    pattern: /edit/{id}
    defaults: { _controller: DentoletiPersonalBundle:Default:edit }