parameters:
#    dentoleti_personal.example.class: Dentoleti\PersonalBundle\Example

services:
#    dentoleti_personal.example:
#        class: %dentoleti_personal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
