parameters:
#    dentoleti_accounting.example.class: Dentoleti\AccountingBundle\Example

services:
#    dentoleti_accounting.example:
#        class: %dentoleti_accounting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
