<?php

namespace Dentoleti\ConsultationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultationStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationStateRepository extends EntityRepository
{
}
