<?php
/*
 *	This file is part of Dentoleti.
 *
 *  Dentoleti is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Dentoleti is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Dentoleti. Read COPYING.txt file for more information.
 *  If it is not present, see <http://www.gnu.org/licenses/>. 
 *
 *  You should find all the information about Dentoleti in http://dentoleti.es
 *
 *	Author Information:
 *		@Author: Luis González Rodríguez
 *		@Email: desarrollo@luismagonzalez.es
 *		@Github: https://github.com/luismagr
 *  	@Author web: http://luismagonzalez.es
 *
 *  File Information:
 *  	@Date:   2014-04-12 09:15:57
 *  	@Last Modified by:   Luis González Rodríguez
 *  	@Last Modified time: 2014-04-12 10:23:52
 * 
 */
namespace Dentoleti\ArticlesBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Dentoleti\ArticlesBundle\Entity\Article;

class Articles extends AbstractFixture implements OrderedFixtureInterface
{
	public function getOrder()
	{
		return 19;
	}

	public function load(ObjectManager $manager)
	{
		$articles = array(
			array('codigo' => 'md 286',
				'description' => 'PROMO EMPASTES NIÑO 15% DTO',
				'price' => '34',
				'vat' => 'NULL',
				'family' => 'Obturaciones',
                'active' => 1,
			),
			array('codigo' => 'MD001',
				'description' => 'LIMPIEZA(OFERTA)',
				'price' => '25',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD002',
				'description' => 'LIMPIEZA',
				'price' => '35',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD003',
				'description' => 'LIMPIEZA GRATUITA',
				'price' => '0',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD004',
				'description' => 'CURETAJE POR CUADRANTE',
				'price' => '55',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD005',
				'description' => 'FLUORIZACION',
				'price' => '25',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD006',
				'description' => 'BLANQUEAMIENTO DENTAL  ( CASA )',
				'price' => '180',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD007',
				'description' => 'BLANQUEAMIENTO DENTAL (EN CLINICA)',
				'price' => '350',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD008',
				'description' => 'BLANQUEAMIENTO DENTAL (EN CLINICA + CASA)',
				'price' => '495',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD009',
				'description' => 'BLANQUEAMIENTO DENTAL POR PIEZA',
				'price' => '90',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD012',
				'description' => 'BLANQUEAMIENTO TETRA PLUS (RECORDATORIO ANUAL)',
				'price' => '350',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD013',
				'description' => 'BLANQUEAMIENTO TETRA PLUS',
				'price' => '900',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD014',
				'description' => 'CONSULTA PROFESIONAL DE URGENCIA',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD015',
				'description' => 'ORTOPANTOMOGRAFIA',
				'price' => '25',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD016',
				'description' => 'ORTOPANTOMOGRAFIA SIN CARGO',
				'price' => '0',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD017',
				'description' => 'FERULA DE DESCARGA',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD018',
				'description' => 'FERULA PERIODONTAL (BARRA LINGUAL)',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD019',
				'description' => 'IRRIGADOR BUCAL',
				'price' => '90',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD020',
				'description' => 'FERULA RADIOLOGICA',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD021',
				'description' => 'FERULA TAC',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD022',
				'description' => 'FERULIZACION POR DIENTE',
				'price' => '40',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD023',
				'description' => 'FERULIZACION POR CUADRANTE',
				'price' => '240',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD024',
				'description' => 'FERULA DESCARGA BLANDA',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD025',
				'description' => 'ODONTOSECCION',
				'price' => '80',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD026',
				'description' => 'FERULA DE RELAJACION MICHIGAN CON GUIA',
				'price' => '170',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD027',
				'description' => 'FERULA DE RELAJACION MICHIGAN SIN GUIA',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD028',
				'description' => 'CURETAJE RASPADO Y ALISADO POR DIENTE',
				'price' => '10',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD029',
				'description' => 'SKYCE (BRILLANTE ESTETICO)',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD030',
				'description' => 'SNOW',
				'price' => '150',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD031',
				'description' => 'OBTURACION SIMPLE',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'Obturaciones',
                'active' => 1,
			),
			array('codigo' => 'MD032',
				'description' => 'OBTURACION COMPLEJA',
				'price' => '40',
				'vat' => 'NULL',
				'family' => 'Obturaciones',
                'active' => 1,
			),
			array('codigo' => 'MD033',
				'description' => 'RECONSTRUCCION',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Obturaciones',
                'active' => 1,
			),
			array('codigo' => 'MD034',
				'description' => 'RECONSTRUCCION CON ESPIGA (TORNILLO)',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD035',
				'description' => 'SELLADOR UNITARIO',
				'price' => '20',
				'vat' => 'NULL',
				'family' => 'Obturaciones',
                'active' => 1,
			),
			array('codigo' => 'MD036',
				'description' => 'SELLADOR UNITARIO',
				'price' => '90',
				'vat' => 'NULL',
				'family' => 'Obturaciones',
                'active' => 1,
			),
			array('codigo' => 'MD037',
				'description' => 'EXODONCIA DIENTE TEMPORAL',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD038',
				'description' => 'EXODONCIA SIMPLE',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD039',
				'description' => 'EXODONCIA RESTO RADICULAR SIMPLE',
				'price' => '45',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD041',
				'description' => 'EXODONCIA CORDAL ',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD042',
				'description' => 'EXODONCIA COMPLEJA',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD043',
				'description' => 'EXODONCIA CORDAL SEMI-INCLUIDO',
				'price' => '80',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD044',
				'description' => 'EXODONCIA CORDAL INCLUIDO',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD045',
				'description' => 'EXODONCIA CON CIRUGIA',
				'price' => '85',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD046',
				'description' => 'CANINO INCLUIDO',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD047',
				'description' => 'ENDODONCIA UNIRRADICULAR (1 CONDUCTO)',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD048',
				'description' => 'ENDODONCIA BIRRADICULAR (2 CONDUCTOS)',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD049',
				'description' => 'ENDODONCIA MULTIRRADICULAR (3 CONDUCTOS)',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD050',
				'description' => 'REENDODONCIA UNIRRADICULAR',
				'price' => '130',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD051',
				'description' => 'REENDODONCIA BIRRADICULAR',
				'price' => '150',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD052',
				'description' => 'REENDODONCIA MULTIRRADICULAR',
				'price' => '170',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD053',
				'description' => 'PULPOTOMIA',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD054',
				'description' => 'PULPECTOMIA + RECONSTRUCCION',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD055',
				'description' => 'PERNO DIENTE',
				'price' => '70',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD056',
				'description' => 'PERNO PREMOLAR',
				'price' => '80',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD057',
				'description' => 'PERNO MOLAR',
				'price' => '90',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD058',
				'description' => 'TORNILLO PARA FIJAR INJERTO(UNIDAD)',
				'price' => '145',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD059',
				'description' => 'DISTRACCION OSEA',
				'price' => '460',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD060',
				'description' => 'APICOFORMACION',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD061',
				'description' => 'CIRUGIA PERIODONCIA CUADRANTE',
				'price' => '250',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD062',
				'description' => 'CIRUGIA PREPROTESICA (VESTIBULOPLASTIA)',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD063',
				'description' => 'FENESTRACION CANINO PARA TRACCION',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD064',
				'description' => 'VENTANA QUIRURGICA',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD065',
				'description' => 'CIRUGIA COLGAJO 1 PIEZA',
				'price' => '25',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD066',
				'description' => 'CIRUGIA COLGAJO 2 PIEZAS',
				'price' => '40',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD067',
				'description' => 'CIRUGIA COLGAJO 3 PIEZAS',
				'price' => '70',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD068',
				'description' => 'CIRUGIA COLGAJO 4 PIEZAS',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD069',
				'description' => 'CIRUGIA COLGAJO 5 PIEZAS',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD070',
				'description' => 'CIRUGIA COLGAJO 6 PIEZAS',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD071',
				'description' => 'CIRUGIA COLGAJO 7 PIEZAS',
				'price' => '170',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD072',
				'description' => 'CIRUGIA COLGAJO 8 PIEZAS',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD073',
				'description' => 'ALARGAMIENTO QUIRURGICO DE LA CORONA POR PIEZA',
				'price' => '160',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD074',
				'description' => 'AUTOINJERTO OSEO DE MENTON O DE RAMA',
				'price' => '620',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD075',
				'description' => 'APICEPTOMIA',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD076',
				'description' => 'GINGIVECTOMIA POR CUADRANTE',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD077',
				'description' => 'CIRUGIA DE RESCATE',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD078',
				'description' => 'REGENERACION OSEA HORIZONTAL O VERTICAL CON MEMBRANA',
				'price' => '350',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD079',
				'description' => 'EXTIRPACION DE TORUS LINGUAL UNILATERAL',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD080',
				'description' => 'EXTIRPACION DE TORUS LINGUAL BILATERAL',
				'price' => '240',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD081',
				'description' => 'EXTIRPACION DE TORUS PALATINO',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD082',
				'description' => 'EXTIRPACION DE EPULIS',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD083',
				'description' => 'EXTIRPACION DE QUISTE O QUISTECTOMIA',
				'price' => '150',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD084',
				'description' => 'CIRUGIA PERIODONCIAL CUADRANTE',
				'price' => '250',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD085',
				'description' => 'GINGIVECTOMIA UNITARIA',
				'price' => '10',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD086',
				'description' => 'FRENECTOMIA',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD087',
				'description' => 'FRENOTOMIA',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD088',
				'description' => 'EMISECCION O AMPUTACION RADICULAR',
				'price' => '70',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD089',
				'description' => 'OSTEOTOMIA PREPOTESICA',
				'price' => '80',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD090',
				'description' => 'REGULARIZACION OSEA',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD091',
				'description' => 'EXPANSION CRESTA OSEA',
				'price' => '280',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD092',
				'description' => 'MEMBRANA REABSORVIBLE',
				'price' => '285',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD093',
				'description' => 'IMPLANTE+CORONA (OFERTA)',
				'price' => '995',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD094',
				'description' => 'IMPLANTE (OFERTA)',
				'price' => '600',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD095',
				'description' => 'IMPLANTE + CORONA',
				'price' => '1200',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD096',
				'description' => 'IMPLANTE',
				'price' => '750',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD097',
				'description' => 'HUESO 1 GRAMO',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD098',
				'description' => 'ELEVACION DE SENO',
				'price' => '1000',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD099',
				'description' => 'FERULA CIRUGIA GUIADA',
				'price' => '410',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD100',
				'description' => 'FERULA QUIRURGICA',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD101',
				'description' => 'PILAR DE ALUMINA PROCERA',
				'price' => '415',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD102',
				'description' => 'PILAR DE TITANIO PROCERA',
				'price' => '295',
				'vat' => 'NULL',
				'family' => 'Implantes',
                'active' => 1,
			),
			array('codigo' => 'MD103',
				'description' => 'SOBREDENTADURA HIBRIDA',
				'price' => '2400',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD104',
				'description' => 'SOBREDENTADURA (OFERTA)',
				'price' => '1800',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD105',
				'description' => 'SOBREDENTADURA HIBRIDA (OFERTA)',
				'price' => '2200',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD106',
				'description' => 'SOBREDENTADURA',
				'price' => '2000',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD107',
				'description' => 'CORONA SOBRE IMPLANTE (OFERTA)',
				'price' => '400',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD108',
				'description' => 'CORONA SOBRE IMPLANTE',
				'price' => '450',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD109',
				'description' => 'CORONA SOBRE IMPLANTE (IMPLANTEDO EN CLINICA)',
				'price' => '650',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD112',
				'description' => 'BARRA TIPO ACKERMAN SOBRE 2 IMPLANTES',
				'price' => '600',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD113',
				'description' => 'BARRA TIPO ACKERMAN SOBRE 3 IMPLANTES',
				'price' => '800',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD114',
				'description' => 'BARRA TIPO ACKERMAN SOBRE 4 IMPLANTES',
				'price' => '1000',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD115',
				'description' => 'BARRA TIPO ACKERMAN SOBRE 5 IMPLANTES',
				'price' => '1200',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD116',
				'description' => 'BARRA TIPO ACKERMAN SOBRE 6 IMPLANTES',
				'price' => '1400',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD117',
				'description' => 'PILAR TIPO LOCATOR',
				'price' => '340',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD118',
				'description' => 'PILAR DE BOLA',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD119',
				'description' => 'PROTESIS REMOVIBLE INF O SUP DE 6 IMPLANTES (PACIENTE EXTERNO)',
				'price' => '3000',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD120',
				'description' => 'PROTESIS REMOVIBLE INF O SUP DE 5 IMPLANTES (PACIENTE EXTERNO)',
				'price' => '2700',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD121',
				'description' => 'PROTESIS REMOVIBLE INF O SUP DE 4 IMPLANTES (PACIENTE EXTERNO)',
				'price' => '2600',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD122',
				'description' => 'PROTESIS REMOVIBLE INF O SUP DE 3 IMPLANTES (PACIENTE EXTERNO)',
				'price' => '2400',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD123',
				'description' => 'PROTESIS INF O SUP HIBRIDA (PACIENTE EXTERNO)',
				'price' => '3000',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD124',
				'description' => 'RECAMBIO DE TEFLONES PARA ATACHES O SOBREDENTADURAS',
				'price' => '55',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,

            ),
			array('codigo' => 'MD125',
				'description' => 'ALARGAMIENTO CORONA POR EXTRUSION ORTODONTICA',
				'price' => '300',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,

            ),
			array('codigo' => 'MD126',
				'description' => 'APARATOLOGIA ELASTICA',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,

            ),
			array('codigo' => 'MD127',
				'description' => 'APARATOLOGIA ACTvat',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,

            ),
			array('codigo' => 'MD128',
				'description' => 'APARATOLOGIA ODONTOPEDIATRICA',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,

            ),
			array('codigo' => 'MD129',
				'description' => 'MANTENEDOR DE ESPACIO',
				'price' => '90',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,

            ),
			array('codigo' => 'MD130',
				'description' => 'HYRAX',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
            ),
			array('codigo' => 'MD131',
				'description' => 'PLACA DE EXPANSION',
				'price' => '210',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,

            ),
			array('codigo' => 'MD132',
				'description' => 'APARATOLOGIA FIJA',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,

            ),
			array('codigo' => 'MD133',
				'description' => 'BARRA TRANSPALATINA',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
            ),
			array('codigo' => 'MD134',
				'description' => 'QUAD HELIX',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
            ),
			array('codigo' => 'MD135',
				'description' => 'DESPEGAR BRACKETS PACIENTE EXTERNO',
				'price' => '55',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
            ),
			array('codigo' => 'MD136',
				'description' => 'APARATOLOGIA FUNCIONAL',
				'price' => '220',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
            ),
			array('codigo' => 'MD137',
				'description' => 'ORTODONCIA CUOTA FIJA TARIFA PLANA',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD138',
				'description' => 'BRAKETS METALICOS INFERIOR',
				'price' => '300',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD139',
				'description' => 'BRAKETS METALICOS SUPERIOR',
				'price' => '300',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD140',
				'description' => 'REVISION ORTODONCIA METALICA',
				'price' => '65',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD141',
				'description' => 'REVISION ORTODONCIA METALICA 1 ARCADA 40 ',
				'price' => '40',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD142',
				'description' => 'BRAKETS ESTETICOS INFERIOR',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD143',
				'description' => 'BRAKETS ESTETICOS SUPERIOR',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD144',
				'description' => 'REVISION ORTODONCIA ESTETICA 70 ',
				'price' => '70',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD145',
				'description' => 'BRAKETS AUTOLIGABLES METALICOS INFERIOR',
				'price' => '450',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD146',
				'description' => 'BRAKETS AUTOLIGABLES METALICOS SUPERIOR',
				'price' => '450',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD147',
				'description' => 'BRAKETS AUTOLIGABLES ESTETICOS INFERIOR',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD148',
				'description' => 'BRAKETS AUTOLIGABLES ESTETICOS SUPERIOR',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD149',
				'description' => 'REVISION ORTODONCIA AUTOLIGABLE 90',
				'price' => '90',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD150',
				'description' => 'BRAKETS ZAFIRO INFERIOR',
				'price' => '450',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD151',
				'description' => 'BRAKETS ZAFIRO SUPERIOR',
				'price' => '450',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD152',
				'description' => 'REVISION ORTODONCIA ZAFIRO',
				'price' => '65',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD153',
				'description' => 'APARATOLOGIA RETENTvat INFERIOR',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD154',
				'description' => 'APARATOLOGIA RETENTvat SUPERIOR',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD155',
				'description' => 'MICROIMPLANTE PARA TRACCION ORTODONCICA',
				'price' => '250',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD156',
				'description' => 'DISYUNTOR PALATINO',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD157',
				'description' => 'STRIPPING',
				'price' => '65',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD158',
				'description' => 'ANCLAJE CORONA TELESCOPICA PROTESIS REMOVIBLE',
				'price' => '75',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD159',
				'description' => 'SOLDAR PERNO+PIEZA',
				'price' => '130',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD160',
				'description' => 'SOLDADURA ESQUELETICO',
				'price' => '90',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD161',
				'description' => 'GANCHO ESTETICO',
				'price' => '75',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD162',
				'description' => 'ESQUELETICOS SUP O INF 1 PIEZA',
				'price' => '350',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD163',
				'description' => 'ESQUELETICOS SUP O INF 2 PIEZAS',
				'price' => '360',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD164',
				'description' => 'ESQUELETICOS SUP O INF 3 PIEZAS',
				'price' => '370',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD165',
				'description' => 'ESQUELETICOS SUP O INF 4 PIEZAS',
				'price' => '380',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD166',
				'description' => 'ESQUELETICOS SUP O INF 5 PIEZAS',
				'price' => '440',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD167',
				'description' => 'ESQUELETICOS SUP O INF 6 PIEZAS',
				'price' => '460',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD168',
				'description' => 'ESQUELETICOS SUP O INF 7 PIEZAS',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD169',
				'description' => 'ESQUELETICOS SUP O INF 8 PIEZAS',
				'price' => '530',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD170',
				'description' => 'ESQUELETICOS SUP O INF 9 PIEZAS',
				'price' => '550',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD171',
				'description' => 'ESQUELETICOS SUP O INF MAS DE 10 PIEZAS',
				'price' => '560',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD172',
				'description' => 'COMPLETA SUP O INF RESINA(CON REJILLA)',
				'price' => '470',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD173',
				'description' => 'REBASE BLANDO',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD174',
				'description' => 'COMPLETA SUP E INF RESINA (CON REJILLA METAL)',
				'price' => '750',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD175',
				'description' => 'COMPOSTURA CON REFUERZO Y MALLA METALICA',
				'price' => '75',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD176',
				'description' => 'MALLA METALICA',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD177',
				'description' => 'CAMBIO TOTAL DE RESINA',
				'price' => '150',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD178',
				'description' => 'AÑADIR GANCHO',
				'price' => '35',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD179',
				'description' => 'AGREGAR PIEZA',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD180',
				'description' => 'ATACHE',
				'price' => '85',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD181',
				'description' => 'REBASE DURO',
				'price' => '70',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD182',
				'description' => 'COMPOSTURA SIMPLE',
				'price' => '40',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD183',
				'description' => 'PARCIAL DE FLEXITE 1 PIEZA',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD184',
				'description' => 'PARCIAL DE FLEXITE 2 PIEZAS',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD185',
				'description' => 'PARCIAL DE FLEXITE 3 PIEZAS',
				'price' => '580',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD186',
				'description' => 'PARCIAL DE FLEXITE 4 PIEZAS',
				'price' => '580',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD187',
				'description' => 'PARCIAL DE FLEXITE 5 PIEZAS',
				'price' => '600',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD188',
				'description' => 'PARCIAL DE FLEXITE 6 PIEZAS',
				'price' => '680',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD189',
				'description' => 'PARCIAL DE FLEXITE 7 PIEZAS',
				'price' => '680',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD190',
				'description' => 'PARCIAL DE FLEXITE 8 PIEZAS',
				'price' => '720',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD191',
				'description' => 'REBASE DE FLEXITE',
				'price' => '150',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD192',
				'description' => 'PARCIAL DE RESINA 1 PIEZA',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD193',
				'description' => 'PARCIAL DE RESINA 2 PIEZAS',
				'price' => '215',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD194',
				'description' => 'PARCIAL DE RESINA 3 PIEZAS',
				'price' => '230',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD195',
				'description' => 'PARCIAL DE RESINA 4 PIEZAS',
				'price' => '280',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD196',
				'description' => 'PARCIAL DE RESINA 5 PIEZAS',
				'price' => '300',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD197',
				'description' => 'PARCIAL DE RESINA 6 PIEZAS',
				'price' => '320',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD198',
				'description' => 'PARCIAL DE RESINA 7 PIEZAS',
				'price' => '350',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD199',
				'description' => 'PARCIAL DE RESINA 8 PIEZAS O MAS PIEZAS',
				'price' => '370',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD200',
				'description' => 'COMPLETA SUP. O INF.DE RESINA',
				'price' => '420',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD201',
				'description' => 'COMPLETA SUPERIOR E INFERIOR DE RESINA',
				'price' => '670',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD202',
				'description' => 'AÑADIR DIENTE PROTESIS METAL',
				'price' => '80',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD203',
				'description' => 'ENCIA ROSA',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD204',
				'description' => 'PALADAR COLADO',
				'price' => '210',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD205',
				'description' => 'RECAMBIO CAZOLETA PARA ATACHE',
				'price' => '45',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD206',
				'description' => 'REFUERZO METALICO',
				'price' => '25',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD207',
				'description' => 'COMPOSTURA COMPLEJA',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD208',
				'description' => 'REPARACION FLEXITE',
				'price' => '175',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD209',
				'description' => 'SOPACHA',
				'price' => '75',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD210',
				'description' => 'CORONA INFANTIL METAL',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD211',
				'description' => 'CORONA PROVISIONAL CLINICA',
				'price' => '10',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD212',
				'description' => 'CORONA TELESCÓPICA (CASQUILLO PRIMARIO)',
				'price' => '130',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD213',
				'description' => 'CORONA TELESCÓPICA(CASQUILLO SECUNDARIO)',
				'price' => '130',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD214',
				'description' => 'RECEMENTADO',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD215',
				'description' => 'CORONA METAL',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD216',
				'description' => 'CORONA METAL CERAMICA',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD217',
				'description' => 'CORONA CERAMICA',
				'price' => '330',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD218',
				'description' => 'CORONA CERAMICA METAL CON ATACHE(UNIDAD)',
				'price' => '345',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD219',
				'description' => 'CORONA PROVISIONAL LABORATORIO',
				'price' => '20',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD220',
				'description' => 'CORONA ZIRCONIO',
				'price' => '400',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD221',
				'description' => 'CEMENTADO CORONA',
				'price' => '30',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD222',
				'description' => 'APOYO OCLUSAL',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD223',
				'description' => 'PUENTE MARYLAND',
				'price' => '360',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD224',
				'description' => 'PUENTE METAL CERAMICA 2 PIEZAS',
				'price' => '400',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD225',
				'description' => 'PUENTE METAL CERAMICA 3 PIEZAS',
				'price' => '600',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD226',
				'description' => 'PUENTE METAL CERAMICA 4 PIEZAS',
				'price' => '800',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD227',
				'description' => 'PUENTE METAL CERAMICA 5 PIEZAS',
				'price' => '1000',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD228',
				'description' => 'PUENTE METAL CERAMICA 6 PIEZAS',
				'price' => '1200',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD229',
				'description' => 'PUENTE METAL CERAMICA 7 PIEZAS',
				'price' => '1400',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD230',
				'description' => 'PUENTE METAL CERAMICA 8 PIEZAS',
				'price' => '1600',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD231',
				'description' => 'PUENTE METAL CERAMICA 9 PIEZAS',
				'price' => '1800',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD232',
				'description' => 'PUENTE METAL CERAMICA 10 PIEZAS',
				'price' => '2000',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD233',
				'description' => 'PUENTE METAL CERAMICA 11 PIEZAS',
				'price' => '2200',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD234',
				'description' => 'PUENTE METAL CERAMICA 12 PIEZAS',
				'price' => '2400',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD235',
				'description' => 'PUENTE CERAMICA 2 PIEZAS',
				'price' => '675',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD236',
				'description' => 'PUENTE CERAMICA 3 PIEZAS',
				'price' => '1000',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD237',
				'description' => 'PUENTE CERAMICA 4 PIEZAS',
				'price' => '1400',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD238',
				'description' => 'PUENTE CERAMICA 5 PIEZAS',
				'price' => '1700',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD239',
				'description' => 'PUENTE CERAMICA 6 PIEZAS',
				'price' => '2000',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD240',
				'description' => 'PUENTE CERAMICA 7 PIEZAS',
				'price' => '2300',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD242',
				'description' => 'PUENTE CERAMICA 9 PIEZAS',
				'price' => '2900',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD243',
				'description' => 'PUENTE CERAMICA 10 PIEZAS',
				'price' => '3200',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD244',
				'description' => 'PUENTE CERAMICA 11 PIEZAS',
				'price' => '3500',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD245',
				'description' => 'PUENTE CERAMICA 12 PIEZAS',
				'price' => '3800',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD246',
				'description' => 'PUENTE PROVISIONAL 2 PIEZAS',
				'price' => '40',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD247',
				'description' => 'PUENTE PROVISIONAL 3 PIEZAS',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD248',
				'description' => 'PUENTE PROVISIONAL 4 PIEZAS',
				'price' => '80',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD249',
				'description' => 'PUENTE PROVISIONAL 5 PIEZAS',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD250',
				'description' => 'PUENTE PROVISIONAL 6 PIEZAS',
				'price' => '120',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD251',
				'description' => 'PUENTE PROVISIONAL 7 PIEZAS',
				'price' => '140',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD252',
				'description' => 'PUENTE PROVISIONAL 8 PIEZAS',
				'price' => '160',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD253',
				'description' => 'PUENTE PROVISIONAL 9 PIEZAS',
				'price' => '180',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD254',
				'description' => 'PUENTE PROVISIONAL 10 PIEZAS',
				'price' => '200',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD255',
				'description' => 'PUENTE ZIRCONIO 2 PIEZAS',
				'price' => '800',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD256',
				'description' => 'PUENTE ZIRCONIO 3 PIEZAS',
				'price' => '1200',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD257',
				'description' => 'PUENTE ZIRCONIO 4 PIEZAS',
				'price' => '1600',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD258',
				'description' => 'PUENTE ZIRCONIO 5 PIEZAS',
				'price' => '2000',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD259',
				'description' => 'PUENTE ZIRCONIO 6 PIEZAS',
				'price' => '2400',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD260',
				'description' => 'PUENTE ZIRCONIO 7 PIEZAS',
				'price' => '2800',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD261',
				'description' => 'PUENTE ZIRCONIO 8 PIEZAS',
				'price' => '3200',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD262',
				'description' => 'PUENTE ZIRCONIO 9 PIEZAS',
				'price' => '3600',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD263',
				'description' => 'PUENTE ZIRCONIO 10 PIEZAS',
				'price' => '4000',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD264',
				'description' => 'CARILLA DE COMPOSITE',
				'price' => '80',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD265',
				'description' => 'CARILLA DE CERAMICA',
				'price' => '270',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD266',
				'description' => 'CAMBIO CERAMICA POR PIEZA',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Prótesis removible',
                'active' => 1,
			),
			array('codigo' => 'MD267',
				'description' => 'CAMBIO DE COLOR MAQUILLAJE POR PIEZA',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD268',
				'description' => 'LEVANTAMIENTO DE PUENTE EXTERNO',
				'price' => '55',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD269',
				'description' => 'ESTUDIO PERIODONTAL',
				'price' => '35',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD270',
				'description' => 'CEMENTADO TEMPORAL',
				'price' => '20',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD271',
				'description' => 'PUENTE CERAMICA 8 PIEZAS',
				'price' => '2600',
				'vat' => 'NULL',
				'family' => 'Prótesis fija',
                'active' => 1,
			),
			array('codigo' => 'MD272',
				'description' => 'EXODONCIA RESTO RADICULAR COMPLEJA',
				'price' => '60',
				'vat' => 'NULL',
				'family' => 'Exodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD273',
				'description' => 'ELEVACION DE SENO ATRAUMATICA',
				'price' => '600',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD274',
				'description' => 'ELAVACION DE SENO BILATERAL',
				'price' => '2000',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD275',
				'description' => 'MENSUALIDAD PLACA DE EXPANSIÓN',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD276',
				'description' => 'RETIRADA DE ORTODONCIA Y RETENEDORES',
				'price' => '150',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD277',
				'description' => 'CORONA ZIRCONIO SOBRE IMPLANTE (OFERTA)           ',
				'price' => '500',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD278',
				'description' => 'CORONA ZIRCONIO SOBRE IMPLANTE',
				'price' => '600',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD279',
				'description' => 'PERNO MUÑÓN COLADO',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Endodoncias',
                'active' => 1,
			),
			array('codigo' => 'MD280',
				'description' => 'PUENTE ZIRCONIO 12 PIEZAS',
				'price' => '4800',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD281',
				'description' => 'EMPASTE (OFERTA)',
				'price' => '35',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD282',
				'description' => 'HUESO 1/2 GRAMO',
				'price' => '100',
				'vat' => 'NULL',
				'family' => 'Cirugía',
                'active' => 1,
			),
			array('codigo' => 'MD283',
				'description' => 'REVISION ZAFIRO BONO',
				'price' => '50',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD284',
				'description' => 'COLOCACION ZAFIRO BONO',
				'price' => '349',
				'vat' => 'NULL',
				'family' => 'Ortodoncia',
                'active' => 1,
			),
			array('codigo' => 'MD285',
				'description' => 'BONO BLANQUEAMIENTO',
				'price' => '59',
				'vat' => 'NULL',
				'family' => 'General',
                'active' => 1,
			),
			array('codigo' => 'MD287',
				'description' => 'ADAPTACION DE PROTESIS SOBRE LOCATOR',
				'price' => '1300',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
			array('codigo' => 'MD288',
				'description' => 'ADAPTACION DE PROTESIS SOBRE BARRA ACKERMAN',
				'price' => '1600',
				'vat' => 'NULL',
				'family' => 'Prótesis sobre implante',
                'active' => 1,
			),
		);

		foreach ($articles as $article_array) {
			$article = new Article();

			$family = $manager->getRepository('DentoletiArticlesBundle:Family')
				->findOneByName($article_array['family']);

			$article->setDescription($article_array['description']);
			$article->setPrice($article_array['price']);
			$article->setVat($article_array['vat']);
			$article->setFamily($family);
			$article->setRegistrationDate(new \DateTime());
            $article->setActive($article_array['active']);

			$manager->persist($article);
		}

		$manager->flush();
	}
}