consultation_add:
    path: /add
    defaults: { _controller:DentoletiConsultationBundle:Default:add }

consultation_edit:
    path: /edit/{id}
    defaults: { _controller:DentoletiConsultationBundle:Default:edit }

consultation_list:
    path: /list
    defaults: { _controller:DentoletiConsultationBundle:Default:list }

consultation_view:
    path: /view/{id}
    defaults: { _controller:DentoletiConsultationBundle:Default:view }