consultation_add:
    path: /add/{doctorId}
    defaults: { _controller:DentoletiConsultationBundle:Default:add }

consultation_edit:
    path: /edit/{id}
    defaults: { _controller:DentoletiConsultationBundle:Default:edit }

consultation_list:
    path: /list
    defaults: { _controller:DentoletiConsultationBundle:Default:list }

consultation_view:
    path: /view/{id}
    defaults: { _controller:DentoletiConsultationBundle:Default:view }

consultation_delete:
    path: /delete/{id}
    defaults: { _controller:DentoletiConsultationBundle:Default:delete }

consultation_erase:
    path: /erase/{id}
    defaults: { _controller:DentoletiConsultationBundle:Default:erase }

consultation_search:
    path: /search
    defaults: { _controller:DentoletiConsultationBundle:Default:search }