imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["dentoleti"]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ["!dentoleti"]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!dentoleti"]
        console:
            type:  console
            channels: ["!dentoleti"]
        dentoleti:
            type:    stream
            path:    "%kernel.logs_dir%/dentoleti.log"
            level:   info
            channels: ["dentoleti"]