dentoleti_personal:
    resource: "@DentoletiPersonalBundle/Resources/config/routing.yml"
    prefix:   /personal

dentoleti_patient:
    resource: "@DentoletiPatientBundle/Resources/config/routing.yml"
    prefix:   /patients

dentoleti_general:
    resource: "@DentoletiGeneralBundle/Resources/config/routing.yml"
    prefix:   /

