parameters:
#    dentoleti_general.example.class: Dentoleti\GeneralBundle\Example

services:
#    dentoleti_general.example:
#        class: %dentoleti_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
