parameters:
#    dentoleti_treatment.example.class: Dentoleti\TreatmentBundle\Example

services:
#    dentoleti_treatment.example:
#        class: %dentoleti_treatment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
