<?php

namespace Dentoleti\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetDetailRepository extends EntityRepository
{
	public function findBudgetDetails($budget)
	{
		$em = $this->getEntityManager();

		$query = $em->createQuery('
			SELECT b, a
			FROM DentoletiBudgetBundle:BudgetDetail b
			JOIN b.article a
			WHERE b.budget = :budget
			');
		$query->setParameter('budget', $budget);
		
		return $query->getResult();
	}

	public function findArticlesOfBudget($budget)
	{
		$em = $this->getEntityManager();

		$query = $em->createQuery('
			SELECT bd, a, b
			FROM DentoletiBudgetBundle:BudgetDetail bd
			JOIN bd.article a
			JOIN bd.budget b
			WHERE bd.budget = :budget
			'); //TODO revisar JOIN bd.budget b. Creo que es innecesario
		
		$query->setParameter('budget', $budget);
		
		return $query->getResult();
	}
}
