/*
 *	This file is part of Dentoleti.
 *
 *  Dentoleti is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Dentoleti is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Dentoleti. Read COPYING.txt file for more information.
 *  If it is not present, see <http://www.gnu.org/licenses/>. 
 *
 *	
 *  @Author: Luis González Rodríguez
 *  @Date:   2014-04-03 16:18:58
 *  @Last Modified by:   Luis González Rodríguez
 *  @Last Modified time: 2014-04-12 08:33:08
 * 
 */
<?php
namespace Dentoleti\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetDetailRepository extends EntityRepository
{
	public function findBudgetDetails($budget)
	{
		$em = $this->getEntityManager();

		$query = $em->createQuery('
			SELECT b, a
			FROM DentoletiBudgetBundle:BudgetDetail b
			JOIN b.article a
			WHERE b.budget = :budget
			');
		$query->setParameter('budget', $budget);
		
		return $query->getResult();
	}

	public function findArticlesOfBudget($budget)
	{
		$em = $this->getEntityManager();

		$query = $em->createQuery('
			SELECT bd, a, b
			FROM DentoletiBudgetBundle:BudgetDetail bd
			JOIN bd.article a
			JOIN bd.budget b
			WHERE bd.budget = :budget
			'); //TODO revisar JOIN bd.budget b. Creo que es innecesario
		
		$query->setParameter('budget', $budget);
		
		return $query->getResult();
	}
}
