<?php

namespace Dentoleti\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRepository extends EntityRepository
{
	public function findNotConfirmed($id)
	{
		$em = $this->getEntityManager();

		$queryBuilder = $em->createQueryBuilder()
			->select('b', 'p')
			->from('DentoletiBudgetBundle:Budget', 'b')
			->join('b.patient', 'p')
			->where('b.confirmed = 0')
			->andwhere('p.id = :id')
			->setParameter('id', $id)
			->getQuery();

		return $queryBuilder->getResult();
	}
}