budget_add:
    pattern:  /add
    defaults: { _controller: DentoletiBudgetBundle:Default:add }

budget_list:
    pattern:  /list
    defaults: { _controller: DentoletiBudgetBundle:Default:list }

budget_search:
    pattern:  /search
    defaults: { _controller: DentoletiBudgetBundle:Default:search }

budget_view:
    pattern: /view/{id}
    defaults: { _controller: DentoletiBudgetBundle:Default:view }

budget_edit:
    pattern: /edit/{id}
    defaults: { _controller: DentoletiBudgetBundle:Default:edit }
