articles_add:
    pattern:  /add
    defaults: { _controller: DentoletiArticlesBundle:Default:add }

articles_search:
    pattern: /search
    defaults: { _controller: DentoletiArticlesBundle:Default:search }

articles_view:
    pattern: /view/{id}
    defaults: { _controller: DentoletiArticlesBundle:Default:view }
