article_add:
    pattern:  /add
    defaults: { _controller: DentoletiArticlesBundle:Default:add }

articles_search:
    pattern: /search
    defaults: { _controller: DentoletiArticlesBundle:Default:search }

article_view:
    pattern: /view/{id}
    defaults: { _controller: DentoletiArticlesBundle:Default:view }

articles_list:
    pattern: /list
    defaults: { _controller: DentoletiArticlesBundle:Default:list }

article_edit:
    pattern: /edit/{id}
    defaults: { _controller: DentoletiArticlesBundle:Default:edit }

article_delete:
    pattern: /delete/{id}
    defaults: { _controller: DentoletiArticlesBundle:Default:delete }

article_erase:
    pattern: /erase/{id}
    defaults: { _controller: DentoletiArticlesBundle:Default:erase }