parameters:
#    dentoleti_articles.example.class: Dentoleti\ArticlesBundle\Example

services:
#    dentoleti_articles.example:
#        class: %dentoleti_articles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
